"""
Failure analysis for Version 3.

Purpose:
This module analyzes the remaining non-passing or non-released cases after
adaptation and recommendation-status classification.

It helps answer:
- Which strategy leaves the most difficult cases?
- Which scenario types cause failures?
- Which severity levels are most problematic?
- Which quality metric causes the failure?
- Why does individual adaptive recommendation not reach 100% pass rate?

This analysis strengthens the discussion section of the thesis.
"""

from __future__ import annotations

from pathlib import Path
from typing import Tuple

import pandas as pd


QUALITY_LIMITS = {
    "mean_gap": 1.0,
    "max_gap": 2.5,
    "parallelism_error": 2.0,
}


def load_recommendation_status_cases(path: str | Path) -> pd.DataFrame:
    """
    Load recommendation-status cases generated by:
    scripts/run_07_recommendation_status_analysis.py
    """

    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(
            f"File not found: {path}. "
            "Run scripts/run_07_recommendation_status_analysis.py first."
        )

    return pd.read_csv(path)


def add_failure_flags(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add metric-level failure flags.

    A case can fail due to:
    - mean_gap exceeding its limit
    - max_gap exceeding its limit
    - parallelism_error exceeding its limit

    Multiple failure reasons can occur at the same time.
    """

    work = df.copy()

    work["fails_mean_gap"] = work["mean_gap"] > QUALITY_LIMITS["mean_gap"]
    work["fails_max_gap"] = work["max_gap"] > QUALITY_LIMITS["max_gap"]
    work["fails_parallelism_error"] = (
        work["parallelism_error"] > QUALITY_LIMITS["parallelism_error"]
    )

    def primary_failure_reason(row: pd.Series) -> str:
        reasons = []

        if row["fails_mean_gap"]:
            reasons.append("mean_gap")

        if row["fails_max_gap"]:
            reasons.append("max_gap")

        if row["fails_parallelism_error"]:
            reasons.append("parallelism_error")

        if not reasons:
            return "none"

        return "+".join(reasons)

    work["primary_failure_reason"] = work.apply(primary_failure_reason, axis=1)

    return work


def create_failure_analysis_by_strategy(df: pd.DataFrame) -> pd.DataFrame:
    """
    Summarize pass/fail and release status by strategy.
    """

    summary = (
        df.groupby("strategy", as_index=False)
        .agg(
            total_cases=("part_case_id", "count"),
            pass_recommended_cases=(
                "recommendation_status",
                lambda x: int((x == "PASS_RECOMMENDED").sum()),
            ),
            manual_review_cases=(
                "recommendation_status",
                lambda x: int((x == "MANUAL_REVIEW").sum()),
            ),
            rework_required_cases=(
                "recommendation_status",
                lambda x: int((x == "REWORK_REQUIRED").sum()),
            ),
            out_of_correction_range_cases=(
                "recommendation_status",
                lambda x: int((x == "OUT_OF_CORRECTION_RANGE").sum()),
            ),
            mean_quality_score=("quality_score", "mean"),
            worst_quality_score=("quality_score", "max"),
            mean_gap_mean=("mean_gap", "mean"),
            max_gap_mean=("max_gap", "mean"),
            parallelism_error_mean=("parallelism_error", "mean"),
        )
    )

    summary["pass_recommended_percent"] = (
        summary["pass_recommended_cases"] / summary["total_cases"] * 100.0
    )
    summary["manual_review_percent"] = (
        summary["manual_review_cases"] / summary["total_cases"] * 100.0
    )
    summary["rework_required_percent"] = (
        summary["rework_required_cases"] / summary["total_cases"] * 100.0
    )
    summary["out_of_correction_range_percent"] = (
        summary["out_of_correction_range_cases"] / summary["total_cases"] * 100.0
    )

    return summary


def create_failure_analysis_by_scenario(df: pd.DataFrame) -> pd.DataFrame:
    """
    Analyze failure/rework/out-of-range cases by scenario and severity.
    """

    difficult_cases = df[df["recommendation_status"] != "PASS_RECOMMENDED"].copy()

    summary = (
        difficult_cases.groupby(
            [
                "strategy",
                "scenario_type",
                "severity_level",
                "disturbance_flag",
                "recommendation_status",
            ],
            as_index=False,
        )
        .agg(
            difficult_cases=("part_case_id", "count"),
            mean_quality_score=("quality_score", "mean"),
            worst_quality_score=("quality_score", "max"),
            mean_gap_mean=("mean_gap", "mean"),
            max_gap_mean=("max_gap", "mean"),
            parallelism_error_mean=("parallelism_error", "mean"),
        )
    )

    total_group_cases = (
        df.groupby(
            ["strategy", "scenario_type", "severity_level", "disturbance_flag"],
            as_index=False,
        )
        .agg(total_group_cases=("part_case_id", "count"))
    )

    summary = summary.merge(
        total_group_cases,
        on=["strategy", "scenario_type", "severity_level", "disturbance_flag"],
        how="left",
    )

    summary["difficult_case_share_percent"] = (
        summary["difficult_cases"] / summary["total_group_cases"] * 100.0
    )

    return summary.sort_values(
        [
            "strategy",
            "difficult_case_share_percent",
            "difficult_cases",
        ],
        ascending=[True, False, False],
    ).reset_index(drop=True)


def create_failure_analysis_by_metric(df: pd.DataFrame) -> pd.DataFrame:
    """
    Count which quality limits are violated.

    This explains whether failures are mainly driven by:
    - mean gap
    - maximum local gap
    - parallelism error
    """

    difficult_cases = df[df["recommendation_status"] != "PASS_RECOMMENDED"].copy()

    rows = []

    for strategy, group in difficult_cases.groupby("strategy"):
        total = len(group)

        rows.append(
            {
                "strategy": strategy,
                "total_difficult_cases": total,
                "fails_mean_gap_cases": int(group["fails_mean_gap"].sum()),
                "fails_max_gap_cases": int(group["fails_max_gap"].sum()),
                "fails_parallelism_error_cases": int(
                    group["fails_parallelism_error"].sum()
                ),
            }
        )

    summary = pd.DataFrame(rows)

    if not summary.empty:
        summary["fails_mean_gap_percent"] = (
            summary["fails_mean_gap_cases"]
            / summary["total_difficult_cases"]
            * 100.0
        )
        summary["fails_max_gap_percent"] = (
            summary["fails_max_gap_cases"]
            / summary["total_difficult_cases"]
            * 100.0
        )
        summary["fails_parallelism_error_percent"] = (
            summary["fails_parallelism_error_cases"]
            / summary["total_difficult_cases"]
            * 100.0
        )

    return summary


def extract_individual_adaptive_failed_cases(df: pd.DataFrame) -> pd.DataFrame:
    """
    Extract the remaining difficult cases after individual adaptive recommendation.
    """

    failed = df[
        (df["strategy"] == "individual_adaptive_setting")
        & (df["recommendation_status"] != "PASS_RECOMMENDED")
    ].copy()

    important_columns = [
        "part_case_id",
        "batch_id",
        "part_id",
        "scenario_type",
        "severity_level",
        "disturbance_flag",
        "recommendation_status",
        "primary_failure_reason",
        "dev_offset",
        "dev_tilt",
        "dev_bend",
        "dev_waviness",
        "dev_noise",
        "dev_twist",
        "fixture_drift",
        "z_adj",
        "theta_adj",
        "locator_offset",
        "mean_gap",
        "max_gap",
        "parallelism_error",
        "rms_deviation",
        "quality_score",
    ]

    available_columns = [col for col in important_columns if col in failed.columns]

    return failed[available_columns].sort_values(
        ["quality_score"], ascending=False
    ).reset_index(drop=True)


def save_failure_analysis(
    recommendation_status_cases_path: str | Path,
    output_dir: str | Path,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Run failure analysis and save output tables.
    """

    recommendation_status_cases_path = Path(recommendation_status_cases_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df = load_recommendation_status_cases(recommendation_status_cases_path)
    df = add_failure_flags(df)

    by_strategy = create_failure_analysis_by_strategy(df)
    by_scenario = create_failure_analysis_by_scenario(df)
    by_metric = create_failure_analysis_by_metric(df)
    individual_failed = extract_individual_adaptive_failed_cases(df)

    by_strategy_path = output_dir / "failure_analysis_by_strategy.csv"
    by_scenario_path = output_dir / "failure_analysis_by_scenario.csv"
    by_metric_path = output_dir / "failure_analysis_by_metric.csv"
    individual_failed_path = output_dir / "individual_adaptive_failed_cases.csv"

    by_strategy.to_csv(by_strategy_path, index=False)
    by_scenario.to_csv(by_scenario_path, index=False)
    by_metric.to_csv(by_metric_path, index=False)
    individual_failed.to_csv(individual_failed_path, index=False)

    return by_strategy, by_scenario, by_metric, individual_failed